AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyBucket:
    Type: AWS::S3::Bucket
Outputs:
  BucketName:
    Description: "New name of the Lab bucket"
    Value: !Ref MyBucket
    Export:
      Name: PotatoBag