AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  AppName:
    Type: String
  Environment:
    Type: String
Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AppName}-${Environment}-bucket'